---
sample_rate: 16000
clip_duration: 10.
fps: 100

train_datasets:
    MAESTRO:
        root: "/datasets/maestro-v3.0.0"
        split: "train"

test_datasets:
    MAESTRO:
        root: "/datasets/maestro-v3.0.0"
        split: "test"
        
model:
    name: Conformer2D
    n_fft: 2048 
    hop_length: 160

train:
    device: "cuda"
    num_workers: 16
    optimizer: AdamW
    lr: 1e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 4
    test_every_n_steps: 10000
    save_every_n_steps: 20000
    training_steps: 200000
    resume_ckpt_path:  # Leave blank if train from scratch